#! /usr/bin/env python
# Get reduced chi square value for NEMESIS model based on mre file
# Nvar is taken from the mre header - not sure if it's always correct

import numpy as np
import sys

if not(len(sys.argv) > 1): sys.exit("Usage: nemesischisq <mre file>" )

f=open(sys.argv[1],'r')

data=f.readlines()

ndata=int(data[1].split()[2])
nvar=int(data[1].split()[3])

obs = np.zeros(ndata)
err = np.zeros(ndata)
mod = np.zeros(ndata)

for i in range(ndata):
   line = data[5+i]
   obs[i]=(float(line.split()[2]))
   err[i]=(float(line.split()[3]))
   mod[i]=(float(line.split()[5]))

print np.sum(((obs-mod)**2/err**2) / (ndata-nvar))
